# Generated by Django 5.0.9 on 2024-10-22 10:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('location', models.CharField(max_length=100)),
                ('short_description', models.CharField(help_text='Max 200 characters', max_length=200)),
                ('salary', models.IntegerField(verbose_name='A salary approximation')),
                ('company', models.CharField(max_length=200)),
                ('thumbnail', models.ForeignKey(blank=True, help_text='Choose a image for your cover', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
