# Generated by Django 5.0.9 on 2024-10-22 10:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='content',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('blockquote', 2), ('list', 4), ('html', 5), ('image', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'template': 'blocks/paragraph.html'}), 2: ('wagtail.blocks.BlockQuoteBlock', (), {'template': 'blocks/blockquote.html'}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.ListBlock', (3,), {'template': 'blocks/list.html'}), 5: ('wagtail.blocks.RawHTMLBlock', (), {'template': 'blocks/html.html'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True),
        ),
    ]
